"use client";

import { useEffect, useState } from "react";
import { getEvents, isSimulatorMode } from "@/lib/device/service";
import { EventList } from "@/components/events/EventList";
import { DeviceEvent } from "@/types/device";

export function EventsClient({ deviceId, deviceName }: { deviceId: string; deviceName: string }) {
  const [events, setEvents] = useState<DeviceEvent[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let cancelled = false;

    async function load() {
      try {
        const evts = await getEvents(deviceId);
        if (!cancelled) {
          setEvents(evts);
          setLoading(false);
        }
      } catch (e) {
        if (!cancelled) {
          setError(e instanceof Error ? e.message : "Unknown error");
          setLoading(false);
        }
      }
    }

    load();

    const interval = isSimulatorMode() ? setInterval(load, 3000) : undefined;

    return () => {
      cancelled = true;
      if (interval) clearInterval(interval);
    };
  }, [deviceId]);

  return (
    <main className="mx-auto max-w-6xl px-4 py-6">
      <h1 className="mb-1 text-lg font-semibold tracking-tight">Event History</h1>
      <p className="mb-4 text-sm text-slate-500">
        Recorded device events for {deviceName}. This is not live telemetry.
      </p>

      {isSimulatorMode() && (
        <div className="mb-4 flex items-center gap-2 rounded-xl border-2 border-dashed border-violet-300 bg-violet-50 px-4 py-2 text-sm font-semibold text-violet-700">
          <span className="flex h-6 w-6 items-center justify-center rounded-full bg-violet-200 text-xs">⚡</span>
          SIMULATION — These events are generated by the simulator, not a physical device.
        </div>
      )}

      {error && (
        <div className="mb-4 rounded-xl border border-status-danger/30 bg-red-50 p-3 text-sm text-status-danger">
          Unable to load events: {error}
        </div>
      )}
      {loading ? (
        <div className="rounded-xl border border-slate-200 bg-white p-6 text-sm text-slate-500">
          Loading events…
        </div>
      ) : (
        <EventList events={events} />
      )}
    </main>
  );
}
